export type DutyGroup = {
  codes: string[];
  title: string;
  items: string[];
};

export type ProcedureEntry = {
  code: string;
  title: string;
  cadence: string;
  owner: string;
  steps: string[];
};

export const dutyGroups: DutyGroup[] = [
  { codes: ["01", "02"], title: "Governance, strategia e vendite", items: ["Definizione di strategie e mission aziendale con riunioni periodiche settimanali", "Supervisione dei processi", "Definizione dei budget futuri", "Controllo del raggiungimento degli obiettivi stabiliti nel budget", "Confronto con i responsabili di uffici e sedi per resoconti e criticità", "Rapporti diretti con i grandi clienti", "Controllo del raggiungimento dei budget con il responsabile ufficio", "Sviluppo della rete commerciale europea", "Sviluppo strategico di nuove filiali o partnership", "Ricerca di nuove tecnologie e attrezzature"] },
  { codes: ["03", "04", "19"], title: "Cantieri, tecnica e formazione", items: ["Gestione esterna dei cantieri Triveneto e dei cantieri direzionali come Varna", "Ricerca di nuove tecnologie e attrezzature", "Formazione generale del reparto tecnico cantieri", "Per il codice 19: affiancamento dei responsabili della logistica esterna per la formazione del personale in cantiere"] },
  { codes: ["05", "07"], title: "Direzione operativa e amministrativa", items: ["Coordinamento delle attività aziendali del proprio ufficio", "Supervisione del personale d’ufficio, responsabilità, tempi e priorità", "Colloqui con nuovo personale dedicato all’ufficio", "Funzioni organizzative e di supervisione degli uffici", "Confronto con i responsabili di uffici e sedi sulle criticità", "Controllo di gestione e rapporti con il consulente economico per il bilancio", "Supporto al responsabile acquisti sui flussi", "Responsabilità della contabilità aziendale generale"] },
  { codes: ["06"], title: "Tecnologia, dati e R&D", items: ["Sviluppo del reparto informatico e integrazione AI con il gestionale", "Invio dati e aggiornamento dispositivi per i report ACCISE ad ADE", "Interfacciamento con sviluppatori software terzi", "Controllo dei report sullo smaltimento rifiuti", "Supervisione dei consumi di carburante e oli", "Ricerca di tecnologie e metodi per migliorare i processi", "Coordinamento del team IT con task e tempi"] },
  { codes: ["08"], title: "Ufficio acquisti", items: ["Posizione indicata come mancante alla data del documento", "Raccolta e previsione delle spese per acquisti centralizzati", "Rendicontazione settimanale a CEO e CFO sulle ottimizzazioni", "Confronto annuale con i fornitori principali", "Bilanciamento dei flussi di spesa con il CFO", "Ricerca di nuovi fornitori per acquisti non strategici"] },
  { codes: ["07", "09"], title: "Direzione sede e commerciale", items: ["Indicazione all’ufficio commerciale delle lavorazioni giornaliere, priorità e tempistiche", "Per il codice 9: ricerca commerciale e gestione dei clienti consolidati", "Organizzazione settimanale dei tempi e delle lavorazioni dell’ufficio commerciale, incluse le urgenze"] },
  { codes: ["10", "12", "20", "23"], title: "Preventivi, ordini e pratiche operative", items: ["Sviluppo commerciale dei preventivi e delle idee di costo", "Per il codice 10: completamento documentale degli ordini con assegnazione di macchine e operatori", "Supporto al commerciale esterno per la chiusura dei contratti aperti", "Per i codici 10 e 12: pratiche quotidiane di ufficio e officina", "Per i codici 20 e 23: comunicazioni giornaliere sui portali Area B e C di Milano", "Formazione reciproca tra i codici 10 e 12 sui metodi di preventivazione nel gestionale"] },
  { codes: ["11"], title: "Risorse umane", items: ["Controllo documentale del personale interno ed esterno", "Pratiche del personale e distacchi", "Rapporti con l’ufficio paghe", "Nuove assunzioni e verifica documentale con alert", "Registrazione paghe nel gestionale fino all’automazione", "Ricerca e pubblicazione di annunci", "Prima selezione con casellario giudiziale e carichi pendenti", "Documento sugli obblighi del personale in cantiere", "Bolli, assicurazioni, multe e sanzioni"] },
  { codes: ["13", "15"], title: "Report lavorazioni", items: ["Controllo e correzione dei rapportini giornalieri con sollecito ai dipendenti", "Supporto alla preventivazione del codice 10", "Supporto al codice 11 per prenotazioni e destinazioni"] },
  { codes: ["14"], title: "Contabilità interna", items: ["Supporto alla referente amministrativa nella contabilità clienti e fornitori", "Controllo analitico delle difformità e segnalazione dei parametri correttivi"] },
  { codes: ["16"], title: "Report, ACCISE e dispositivi", items: ["Formazione sui rapportini dei dipendenti con i codici 13 e 15", "Controllo giornaliero dei consumi di carburante", "Comunicazione dei dati per il recupero ACCISE", "Verifica giornaliera dei dispositivi installati sui macchinari", "Sviluppo e controllo delle bolle digitali di ingresso e uscita"] },
  { codes: ["17"], title: "Sicurezza e formazione", items: ["Formazione dei collaboratori interni sulla sicurezza", "Formazione di dipendenti e clienti sull’uso di macchine a noleggio a freddo", "Benestare documentale al responsabile logistica generale", "Interfaccia con la logistica per collaudi e manutenzioni", "Controllo anticipato dei portali cliente e degli accessi", "Aggiornamento continuo della formazione del personale"] },
  { codes: ["18"], title: "Logistica generale", items: ["Corrispondenza di macchine e attrezzature dei magazzini con il codice 26", "Sviluppo dei sistemi di immagazzinamento, kit, ceste e kit pompe", "Formazione e controllo dei logisti interni di Treviso e Milano", "Anticipo del fabbisogno ricambi per le officine", "Controllo della dislocazione in sicurezza di mezzi e attrezzature", "Programmazione e registrazione delle manutenzioni e della messa in sicurezza"] },
  { codes: ["19"], title: "Logistica esterna e formazione cantieri", items: ["Coordinamento delle attività esterne dei cantieri", "Percorso di formazione bisettimanale nelle sedi di Treviso e Milano"] },
  { codes: ["20", "23"], title: "Logistica interna", items: ["Programmazione settimanale e modifica giornaliera della logistica di mezzi, attrezzature e persone", "Controllo della merce di rientro con i codici 26 e 27", "Verifica della corrispondenza documentale tra vendita e reso", "Sollecito del personale per i rapportini giornalieri"] },
  { codes: ["21", "22"], title: "Officine", items: ["Organizzazione dell’officina e anticipo dei ricambi con il codice 18", "Responsabilità del calendario tagliandi e manutenzioni", "Supporto tecnico alle richieste di cantiere", "Manutenzioni ordinarie e straordinarie", "Aggiornamento della checklist giornaliera tramite app"] },
  { codes: ["24"], title: "Logistica esterna Bareggio", items: ["Formazione del personale alla gestione autonoma di mezzi e attrezzature", "Percorso formativo bisettimanale nelle sedi", "Programmazione bisettimanale delle lavorazioni nel gestionale"] },
  { codes: ["25"], title: "Verniciatura e officina", items: ["Manutenzione e verniciatura bisettimanale delle attrezzature", "Aggiornamento checklist con tempi e tipologie di lavoro", "Supporto alle attività di carico e scarico", "Realizzazione di attrezzature speciali interne ed esterne"] },
  { codes: ["26", "27"], title: "Magazzino e rifornimenti", items: ["Controllo della dislocazione e dello stato delle attrezzature", "Responsabilità di quantità, qualità, pulizia e ordine delle aree", "Verifica delle etichettature", "Produzione dei documenti di trasporto con il logista", "Responsabilità di carico e scarico", "Verifica documentale delle merci in arrivo", "Smaltimento rifiuti in coordinamento con il codice 6"] },
  { codes: ["28"], title: "Lavaggio", items: ["Lavaggio di mezzi e attrezzature su task programmati e straordinari", "Supporto alle operazioni di carico e scarico"] },
  { codes: ["29", "30"], title: "Autisti muletti", items: ["Carico, scarico e immagazzinamento nella posizione assegnata, coordinandosi con 26 e 27", "Responsabilità della carica giornaliera di muletti e trainatori"] },
  { codes: ["31"], title: "Consegne, ritiri e transfert", items: ["Consegna e ritiro delle merci da cantieri e sedi", "Confronto visivo e tramite app con bolle di consegna e ritiro", "Segnalazione delle non conformità tramite app", "Responsabilità del terminale RFID", "Esecuzione degli itinerari indicati dal gestionale"] },
  { codes: ["32"], title: "Area cantieri Centro Italia", items: ["Ricerca commerciale e gestione clienti", "Formalizzazione contratti e gestione esecutiva con 26 e 20", "Creazione preventivi tramite app e gestionale", "Analisi settimanale dei tassi di chiusura"] },
  { codes: ["33"], title: "Autisti betoniere", items: ["Ritiro del carico presso le centrali di betonaggio e scarico a destinazione", "Rapportini tramite app con quantità pompate, orari e tempi", "Verifica delle anomalie con il codice 13"] },
  { codes: ["34", "35"], title: "Addetti preposti", items: ["Presa in consegna e organizzazione di allestimento e disallestimento", "Responsabilità dei rapportini propri e del personale del codice 37", "Certificazione della linea di pompaggio tramite dispositivo mobile", "Responsabilità di squadra, sicurezza e DPI", "Verifica di mezzi e attrezzature con il codice 31", "Responsabilità dei dati e delle lavorazioni fornite al cliente"] },
  { codes: ["36"], title: "Cantiere Varna", items: ["Esecuzione delle lavorazioni previste da contratto", "Reportistica giornaliera di costi e lavorazioni", "Manutenzione ordinaria di mezzi e attrezzature in cantiere"] },
  { codes: ["37"], title: "Addetti qualificati e comuni", items: ["Supporto ai codici 34 e 35 nelle fasi di allestimento, pompaggio e disallestimento", "Rapportini giornalieri tramite app", "Lavaggio e manutenzione giornaliera di mezzi e attrezzature", "Ordine, pulizia e precisione dell’impianto", "Segnalazione immediata delle anomalie ai codici 34 e 35"] },
];

export const procedures: ProcedureEntry[] = [
  { code: "A", title: "Flusso CEO - CCO e avvio commessa", cadence: "Continuo / per commessa", owner: "CEO e CCO", steps: ["Ruoli, responsabilità e corretta esecuzione tecnica", "Trasferimento di preventivo, progetto, budget, tempi e accordi", "Approvazione delle varianti economiche o contrattuali", "Controllo periodico di avanzamento, tempi, costi e criticità"] },
  { code: "B", title: "Budget, tesoreria e reporting", cadence: "Settimanale - trimestrale", owner: "CFO-COO e CEO", steps: ["Budget e controllo economico mensile", "Pagamenti e tesoreria settimanale", "Marginalità e commesse ogni 15 giorni", "Organizzazione e processi mensili", "Reporting direzionale trimestrale"] },
  { code: "C", title: "Governance tecnologica e R&D", cadence: "Settimanale - trimestrale", owner: "CEO e CTO-R&D", steps: ["Allineamento strategico mensile", "Avanzamento progetti R&D settimanale", "Investimenti e priorità tecnologiche", "Escalation delle criticità entro 24 ore", "Governance ERP, CRM, dati e cybersecurity", "Sviluppo, test e validazione delle soluzioni", "Reporting e revisione della roadmap"] },
  { code: "D", title: "Coordinamento e performance delle sedi", cadence: "Settimanale - trimestrale", owner: "CFO-COO e responsabili sedi", steps: ["Confronto operativo settimanale", "Controllo economico mensile", "Budget e autorizzazione delle spese", "Fabbisogni del personale", "Escalation entro 24 ore", "Rendimenti, risorse condivise e performance trimestrali"] },
  { code: "E", title: "Personale, presenze e costi", cadence: "Continuo - trimestrale", owner: "HR e CFO-COO", steps: ["Alert giornalieri su presenze e anomalie", "Controllo del costo del personale", "Analisi dei fabbisogni e delle soglie HR", "Scadenze automatiche 15-30-60 giorni", "Produttività e costo per area", "Gestione delle criticità e previsione del budget"] },
  { code: "F", title: "Acquisti e fornitori", cadence: "Giornaliero - trimestrale", owner: "Ufficio acquisti e CFO-COO", steps: ["Pianificazione settimanale di fabbisogni e ordini", "Autorizzazioni automatiche o su richiesta", "Alert immediati su prezzi e costi", "Gestione trimestrale dei fornitori", "Alert giornalieri su ordini e consegne", "Acquisti urgenti e fuori budget", "Analisi mensile di saving e performance"] },
  { code: "G", title: "Contabilità e controllo amministrativo", cadence: "Giornaliero - trimestrale", owner: "Contabilità e CFO-COO", steps: ["Quadratura contabile giornaliera", "Crediti e scaduti settimanali", "Pianificazione pagamenti fornitori", "Attribuzione documenti a sedi, reparti e commesse", "Chiusura mensile entro il giorno 10", "Controllo liquidità e tesoreria", "Alert amministrativi e verifica scostamenti", "Riunione amministrativa mensile"] },
  { code: "H", title: "Flussi dati e pratiche ADG/ADE", cadence: "Continuo - trimestrale", owner: "Ufficio dati e CTO", steps: ["Acquisizione automatica dei flussi", "Gestione giornaliera degli alert", "Validazione delle pratiche prima dell’invio", "Monitoraggio bisettimanale ADG/ADE", "Scadenze automatiche 30-15-7 giorni", "Controllo mensile recuperi ACCISE", "Analisi trimestrale degli errori e delle automazioni"] },
  { code: "H1", title: "Pianificazione e rilascio software", cadence: "Settimanale - trimestrale", owner: "CTO e sviluppatore", steps: ["Piano settimanale di attività e priorità", "Controllo di RFID, CANbus, GPS, gestionale e checklist", "Revisione mensile della roadmap", "Flusso requisito - sviluppo - test - validazione - rilascio", "Classificazione delle personalizzazioni", "Riepilogo mensile di avanzamento"] },
  { code: "I", title: "Sviluppo futuro", cadence: "Da definire", owner: "Direzione", steps: ["Nel documento originale la procedura è indicata come da fare in funzione dello sviluppo"] },
  { code: "L", title: "Dati personale e formazione", cadence: "Continuo / alert 90-60-30-15-7 giorni", owner: "HR e Sicurezza", steps: ["Aggiornamento dati del personale", "Controllo formazione, abilitazioni e documenti", "Intervento sulle anomalie segnalate automaticamente"] },
  { code: "M", title: "Accessi, distacchi e preparazione cantieri", cadence: "Settimanale / previsionale", owner: "HR, Sicurezza, Operazioni e Commerciale", steps: ["Portali clienti e abilitazioni", "Previsione cantieri, personale e distacchi a 30-60-90 giorni", "Coinvolgimento commerciale immediato", "Controllo automatico degli spostamenti urgenti", "Verifica accessi T-7 e T-2 giorni", "Riunione settimanale sulle eccezioni"] },
  { code: "N", title: "Coordinamento logistico tra sedi", cadence: "Giornaliero - 30 giorni", owner: "Logistica generale e sedi", steps: ["Punto operativo giornaliero", "Programmazione settimanale dei fabbisogni", "Trasferimenti pianificati 48-72 ore prima", "Alert su materiali mancanti e urgenze", "Gestione richieste improvvise", "Controllo scorte settimanale", "Previsione picchi a 15-30 giorni", "Confronto settimanale Milano-Treviso"] },
  { code: "O", title: "Officina e manutenzioni", cadence: "Giornaliero - settimanale", owner: "Officina e Logistica", steps: ["Manutenzioni ordinarie da checklist", "Ticket immediati per manutenzioni straordinarie", "Intervento urgente per blocco macchina", "Preparazione ricambi e materiali", "Dotazione ufficiale dell’officina", "Segnalazione attrezzature mancanti", "Stato giornaliero mezzi e riunione settimanale"] },
  { code: "P", title: "Trattamento e conformità dei materiali", cadence: "Giornaliero - settimanale", owner: "Logistica e reparti", steps: ["Programmazione dei materiali da trattare", "Presa in carico giornaliera", "Checklist lavaggio, riparazione e verniciatura", "Controllo standard prima del magazzino", "Identificazione RFID", "Trasferimenti 48-72 ore prima", "Blocco automatico delle non conformità", "Previsione fabbisogni 15-30 giorni", "Punto settimanale Logistica-Reparti"] },
  { code: "Q", title: "Logistica automatizzata dall’ordine al rientro", cadence: "Tempo reale / settimanale", owner: "Logistica generale e di zona", steps: ["Pianificazione automatica dall’ordine cliente", "Previsione risorse a 7-15-30 giorni", "Preparazione materiale 48-72 ore prima", "Alert automatici ai reparti", "Preimpostazione e controllo del carico", "Verifica RFID", "Controllo del materiale in cantiere", "Ticket automatici dal cantiere", "Gestione ritiri e rientri", "Previsione della disponibilità futura", "Dashboard operativa unica", "Riunione settimanale sulle eccezioni"] },
  { code: "R", title: "Arrivo merce e scarico", cadence: "Ad ogni consegna", owner: "Preposto e autista", steps: ["Affiancamento dell’autista", "Verifica della corrispondenza del materiale consegnato"] },
  { code: "R1", title: "Controllo RFID", cadence: "Ad ogni movimentazione", owner: "Preposto", steps: ["Controllo del materiale consegnato, presente, installato e da ritirare", "Aggiornamento automatico del gestionale"] },
  { code: "R2", title: "Certificazione linea di pompaggio", cadence: "Prima del pompaggio e del rientro", owner: "Preposto", steps: ["Verifica RFID della composizione della linea", "Certificazione di tubazioni, morsetti e coppiglie", "Segnalazione immediata delle anomalie", "Controllo del materiale al ritiro e chiusura digitale"] },
  { code: "S", title: "Ciclo autobetoniere automatizzato", cadence: "Continuo / fine giornata", owner: "Autisti betoniere", steps: ["Inizio giornata da GPS e CAN bus", "Carico CLS con scansione della bolla", "Tracciamento automatico di trasporto e arrivo", "Registrazione automatica dei carichi successivi", "Segnalazione solo delle anomalie", "Rapportino di fine giornata generato automaticamente"] },
  { code: "T", title: "Gestione impianto e cantiere", cadence: "Giornaliero - mensile", owner: "Responsabile di commessa", steps: ["Pianificazione giornaliera e settimanale", "Gestione impianto e produzione CLS", "Trasporto e pompaggio intracantiere", "Movimentazione inerti, pulizia e manutenzione", "Turni straordinari, notturni e festivi", "Gestione anomalie e fermo impianto", "Raccolta dati e rapportini", "Quadratura settimanale o mensile", "Riunione operativa settimanale"] },
  { code: "U1", title: "Coordinamento operativo del preposto", cadence: "Giornaliero / continuo", owner: "Preposto", steps: ["Briefing e assegnazione delle attività", "Controllo di avanzamento", "Programmazione delle pause utili", "Controllo attrezzature e materiali", "Rapportino giornaliero di fine turno", "Chiusura giornata e passaggio consegne"] },
  { code: "U2", title: "Sicurezza, qualità ed escalation", cadence: "Continuo / immediato", owner: "Preposto e operatori", steps: ["Pulizia e cura delle attrezzature", "Sicurezza e uso dei DPI", "Segnalazione immediata delle anomalie", "Gestione degli operatori qualificati e operativi", "Controllo qualità delle lavorazioni", "Gestione degli imprevisti ed escalation"] },
];

export function dutiesForCode(code: string) {
  return dutyGroups.flatMap((group) => group.codes.includes(code) ? group.items : []);
}
