export type DutyGroup = {
  codes: string[];
  title: string;
  items: string[];
};

export type ProcedureEntry = {
  code: string;
  title: string;
  cadence: string;
  owner: string;
  steps: string[];
};

export const dutyGroups: DutyGroup[] = [
  { codes: ["01", "02"], title: "Governance, strategia e vendite", items: ["Definizione di strategie e mission aziendale con riunioni periodiche settimanali", "Supervisione dei processi", "Definizione dei budget futuri", "Controllo del raggiungimento degli obiettivi stabiliti nel budget", "Confronto con i responsabili di uffici e sedi per resoconti e criticità", "Rapporti diretti con i grandi clienti", "Controllo del raggiungimento dei budget con il responsabile ufficio", "Sviluppo della rete commerciale europea", "Sviluppo strategico di nuove filiali o partnership", "Ricerca di nuove tecnologie e attrezzature"] },
  { codes: ["03", "04", "19"], title: "Cantieri, tecnica e formazione", items: ["Gestione esterna dei cantieri Triveneto e dei cantieri direzionali come Varna", "Ricerca di nuove tecnologie e attrezzature", "Formazione generale del reparto tecnico cantieri", "Per il codice 19: affiancamento dei responsabili della logistica esterna per la formazione del personale in cantiere"] },
  { codes: ["05", "07"], title: "Direzione operativa e amministrativa", items: ["Coordinamento delle attività aziendali del proprio ufficio", "Supervisione del personale d’ufficio, responsabilità, tempi e priorità", "Colloqui con nuovo personale dedicato all’ufficio", "Funzioni organizzative e di supervisione degli uffici", "Confronto con i responsabili di uffici e sedi sulle criticità", "Controllo di gestione e rapporti con il consulente economico per il bilancio", "Supporto al responsabile acquisti sui flussi", "Responsabilità della contabilità aziendale generale"] },
  { codes: ["06"], title: "Tecnologia, dati e R&D", items: ["Sviluppo del reparto informatico e integrazione AI con il gestionale", "Invio dati e aggiornamento dispositivi per i report ACCISE ad ADE", "Interfacciamento con sviluppatori software terzi", "Controllo dei report sullo smaltimento rifiuti", "Supervisione dei consumi di carburante e oli", "Ricerca di tecnologie e metodi per migliorare i processi", "Coordinamento del team IT con task e tempi"] },
  { codes: ["08"], title: "Ufficio acquisti", items: ["Posizione indicata come mancante alla data del documento", "Raccolta e previsione delle spese per acquisti centralizzati", "Rendicontazione settimanale a CEO e CFO sulle ottimizzazioni", "Confronto annuale con i fornitori principali", "Bilanciamento dei flussi di spesa con il CFO", "Ricerca di nuovi fornitori per acquisti non strategici"] },
  { codes: ["07", "09"], title: "Direzione sede e commerciale", items: ["Indicazione all’ufficio commerciale delle lavorazioni giornaliere, priorità e tempistiche", "Per il codice 9: ricerca commerciale e gestione dei clienti consolidati", "Organizzazione settimanale dei tempi e delle lavorazioni dell’ufficio commerciale, incluse le urgenze"] },
  { codes: ["10", "12", "20", "23"], title: "Preventivi, ordini e pratiche operative", items: ["Sviluppo commerciale dei preventivi e delle idee di costo", "Per il codice 10: completamento documentale degli ordini con assegnazione di macchine e operatori", "Supporto al commerciale esterno per la chiusura dei contratti aperti", "Per i codici 10 e 12: pratiche quotidiane di ufficio e officina", "Per i codici 20 e 23: comunicazioni giornaliere sui portali Area B e C di Milano", "Formazione reciproca tra i codici 10 e 12 sui metodi di preventivazione nel gestionale"] },
  { codes: ["11"], title: "Risorse umane", items: ["Controllo documentale del personale interno ed esterno", "Pratiche del personale e distacchi", "Rapporti con l’ufficio paghe", "Nuove assunzioni e verifica documentale con alert", "Registrazione paghe nel gestionale fino all’automazione", "Ricerca e pubblicazione di annunci", "Prima selezione con casellario giudiziale e carichi pendenti", "Documento sugli obblighi del personale in cantiere", "Bolli, assicurazioni, multe e sanzioni"] },
  { codes: ["13", "15"], title: "Report lavorazioni", items: ["Controllo e correzione dei rapportini giornalieri con sollecito ai dipendenti", "Supporto alla preventivazione del codice 10", "Supporto al codice 11 per prenotazioni e destinazioni"] },
  { codes: ["14"], title: "Contabilità interna", items: ["Supporto alla referente amministrativa nella contabilità clienti e fornitori", "Controllo analitico delle difformità e segnalazione dei parametri correttivi"] },
  { codes: ["16"], title: "Report, ACCISE e dispositivi", items: ["Formazione sui rapportini dei dipendenti con i codici 13 e 15", "Controllo giornaliero dei consumi di carburante", "Comunicazione dei dati per il recupero ACCISE", "Verifica giornaliera dei dispositivi installati sui macchinari", "Sviluppo e controllo delle bolle digitali di ingresso e uscita"] },
  { codes: ["17"], title: "Sicurezza e formazione", items: ["Formazione dei collaboratori interni sulla sicurezza", "Formazione di dipendenti e clienti sull’uso di macchine a noleggio a freddo", "Benestare documentale al responsabile logistica generale", "Interfaccia con la logistica per collaudi e manutenzioni", "Controllo anticipato dei portali cliente e degli accessi", "Aggiornamento continuo della formazione del personale"] },
  { codes: ["18"], title: "Logistica generale", items: ["Corrispondenza di macchine e attrezzature dei magazzini con il codice 26", "Sviluppo dei sistemi di immagazzinamento, kit, ceste e kit pompe", "Formazione e controllo dei logisti interni di Treviso e Milano", "Anticipo del fabbisogno ricambi per le officine", "Controllo della dislocazione in sicurezza di mezzi e attrezzature", "Programmazione e registrazione delle manutenzioni e della messa in sicurezza"] },
  { codes: ["19"], title: "Logistica esterna e formazione cantieri", items: ["Coordinamento delle attività esterne dei cantieri", "Percorso di formazione bisettimanale nelle sedi di Treviso e Milano"] },
  { codes: ["20", "23"], title: "Logistica interna", items: ["Programmazione settimanale e modifica giornaliera della logistica di mezzi, attrezzature e persone", "Controllo della merce di rientro con i codici 26 e 27", "Verifica della corrispondenza documentale tra vendita e reso", "Sollecito del personale per i rapportini giornalieri"] },
  { codes: ["21", "22"], title: "Officine", items: ["Organizzazione dell’officina e anticipo dei ricambi con il codice 18", "Responsabilità del calendario tagliandi e manutenzioni", "Supporto tecnico alle richieste di cantiere", "Manutenzioni ordinarie e straordinarie", "Aggiornamento della checklist giornaliera tramite app"] },
  { codes: ["24"], title: "Logistica esterna Bareggio", items: ["Formazione del personale alla gestione autonoma di mezzi e attrezzature", "Percorso formativo bisettimanale nelle sedi", "Programmazione bisettimanale delle lavorazioni nel gestionale"] },
  { codes: ["25"], title: "Verniciatura e officina", items: ["Manutenzione e verniciatura bisettimanale delle attrezzature", "Aggiornamento checklist con tempi e tipologie di lavoro", "Supporto alle attività di carico e scarico", "Realizzazione di attrezzature speciali interne ed esterne"] },
  { codes: ["26", "27"], title: "Magazzino e rifornimenti", items: ["Controllo della dislocazione e dello stato delle attrezzature", "Responsabilità di quantità, qualità, pulizia e ordine delle aree", "Verifica delle etichettature", "Produzione dei documenti di trasporto con il logista", "Responsabilità di carico e scarico", "Verifica documentale delle merci in arrivo", "Smaltimento rifiuti in coordinamento con il codice 6"] },
  { codes: ["28"], title: "Lavaggio", items: ["Lavaggio di mezzi e attrezzature su task programmati e straordinari", "Supporto alle operazioni di carico e scarico"] },
  { codes: ["29", "30"], title: "Autisti muletti", items: ["Carico, scarico e immagazzinamento nella posizione assegnata, coordinandosi con 26 e 27", "Responsabilità della carica giornaliera di muletti e trainatori"] },
  { codes: ["31"], title: "Consegne, ritiri e transfert", items: ["Consegna e ritiro delle merci da cantieri e sedi", "Confronto visivo e tramite app con bolle di consegna e ritiro", "Segnalazione delle non conformità tramite app", "Responsabilità del terminale RFID", "Esecuzione degli itinerari indicati dal gestionale"] },
  { codes: ["32"], title: "Area cantieri Centro Italia", items: ["Ricerca commerciale e gestione clienti", "Formalizzazione contratti e gestione esecutiva con 26 e 20", "Creazione preventivi tramite app e gestionale", "Analisi settimanale dei tassi di chiusura"] },
  { codes: ["33"], title: "Autisti betoniere", items: ["Ritiro del carico presso le centrali di betonaggio e scarico a destinazione", "Rapportini tramite app con quantità pompate, orari e tempi", "Verifica delle anomalie con il codice 13"] },
  { codes: ["34", "35"], title: "Addetti preposti", items: ["Presa in consegna e organizzazione di allestimento e disallestimento", "Responsabilità dei rapportini propri e del personale del codice 37", "Certificazione della linea di pompaggio tramite dispositivo mobile", "Responsabilità di squadra, sicurezza e DPI", "Verifica di mezzi e attrezzature con il codice 31", "Responsabilità dei dati e delle lavorazioni fornite al cliente"] },
  { codes: ["36"], title: "Cantiere Varna", items: ["Esecuzione delle lavorazioni previste da contratto", "Reportistica giornaliera di costi e lavorazioni", "Manutenzione ordinaria di mezzi e attrezzature in cantiere"] },
  { codes: ["37"], title: "Addetti qualificati e comuni", items: ["Supporto ai codici 34 e 35 nelle fasi di allestimento, pompaggio e disallestimento", "Rapportini giornalieri tramite app", "Lavaggio e manutenzione giornaliera di mezzi e attrezzature", "Ordine, pulizia e precisione dell’impianto", "Segnalazione immediata delle anomalie ai codici 34 e 35"] },
];

export const procedures: ProcedureEntry[] = [
  { code: "A", title: "Flusso CEO - CCO e avvio commessa", cadence: "Continuo / per commessa", owner: "CEO e CCO", steps: ["Ruoli e responsabilità — il CEO gestisce strategia, clienti, budget e marginalità; il CCO organizza cantieri, squadre, materiali e corretta esecuzione tecnica.", "Avvio commessa — prima dell’apertura del cantiere il CEO trasferisce al CCO preventivo, progetto, budget, tempi e accordi con il cliente.", "Gestione varianti e costi — il CCO valuta tecnicamente imprevisti ed extra; ogni variazione economica o contrattuale deve essere approvata dal CEO.", "Controllo cantieri — il CCO aggiorna periodicamente il CEO su avanzamento, tempi, costi, criticità ed eventuali scostamenti dal budget."] },
  { code: "B", title: "Budget, tesoreria e reporting", cadence: "Settimanale - trimestrale", owner: "CFO-COO e CEO", steps: ["Budget e controllo economico — mensile, entro il 10: consuntivo, scostamenti dal budget, cash flow e andamento aggiornato.", "Pagamenti e tesoreria — ogni lunedì: situazione bancaria, pagamenti previsti, incassi attesi e fabbisogno finanziario delle successive quattro settimane.", "Marginalità e commesse — ogni 15 giorni: marginalità, costi fuori budget, crediti e situazioni economicamente critiche ricavate dal gestionale.", "Organizzazione e processi — entro fine mese: inefficienze, carichi di lavoro, procedure interne e azioni correttive con responsabilità e scadenze.", "Reporting direzionale — entro 15 giorni dalla chiusura trimestrale: report economici e operativi, obiettivi e piano d’azione del trimestre successivo."] },
  { code: "C", title: "Governance tecnologica e R&D", cadence: "Settimanale - trimestrale", owner: "CEO e CTO-R&D", steps: ["Allineamento strategico CEO–CTO R&D — mensile: priorità, roadmap, obiettivi, iniziative e report dal gestionale.", "Avanzamento progetti R&D — settimanale: stato, tempi, costi, risorse, ritardi e criticità.", "Investimenti tecnologici — mensile o al bisogno: software, hardware, prototipi, consulenze e tecnologie di interfacciamento dati.", "Gestione priorità tecnologiche — settimanale: attività urgenti, strategiche e a maggiore impatto.", "Criticità — immediata o entro 24 ore: blocchi, rischi tecnologici, sicurezza, ritardi rilevanti e problemi sui sistemi installati.", "Governance sistemi, dati e cybersecurity — mensile: ERP, CRM, infrastruttura IT, automazioni, integrazioni, sicurezza e qualità dei dati.", "Sviluppo e validazione — per ogni progetto con verifica mensile: idea, analisi, prototipo, test, validazione e implementazione.", "Reporting tecnologico al CEO — mensile: soluzioni, budget, progetti, rischi, innovazione e decisioni necessarie.", "Revisione roadmap — trimestrale: obiettivi raggiunti e piano tecnologico dei successivi 3–12 mesi."] },
  { code: "D", title: "Coordinamento e performance delle sedi", cadence: "Settimanale - trimestrale", owner: "CFO-COO e responsabili sedi", steps: ["Confronto operativo tra sedi — settimanale: attività, carichi, criticità, personale, priorità e soluzioni.", "Controllo economico — mensile: costi, ricavi, marginalità, scostamenti dal budget e spese straordinarie.", "Budget e autorizzazione spese — mensile o al bisogno: limiti dei singoli uffici e soglie autorizzative CFO-COO.", "Personale e fabbisogni operativi — mensile: organico, assenze, nuove risorse, straordinari e redistribuzione carichi.", "Criticità ed escalation — immediata o entro 24 ore: problemi economici, organizzativi, clienti rilevanti, personale e blocchi operativi.", "Rendimenti e coordinamento — mensile: fatturato, costi, produttività, marginalità, commesse, tempi, indicatori, risorse condivise e formazione.", "Andamento economico e operativo — trimestrale: previsioni di fatturato, costi, personale, investimenti e carichi per sede.", "Revisione performance sedi — trimestrale: risultati, criticità, obiettivi e azioni correttive per il trimestre successivo."] },
  { code: "E", title: "Personale, presenze e costi", cadence: "Continuo - trimestrale", owner: "HR e CFO-COO", steps: ["Presenze e anomalie — giornaliero con alert automatico: assenze, ferie, ritardi, mancate timbrature, straordinari anomali e soglie; HR interviene e informa COO/CFO nei casi rilevanti.", "Costo del personale — settimanale/mensile: budget ore, straordinari, ferie residue, costo per reparto o sede e scostamenti.", "Fabbisogno personale — mensile: carichi, saturazione, assenze previste, assunzioni o redistribuzione; allerta CFO-COO.", "Superamento soglie HR — immediato/entro 24 ore: straordinari, assenteismo, ferie accumulate, scadenze contrattuali, periodi di prova e anomalie costo, con comunicazioni a CEO e CFO-COO.", "Scadenze contratti e documenti — alert 15/30/60 giorni: rinnovi, certificazioni, visite mediche, formazione, permessi e documentazione.", "Produttività e costo per area — mensile: costo, produttività, ore, assenze e scostamenti per reparto, sede o centro di costo.", "Criticità del personale — immediata/settimanale: HR gestisce le ordinarie; quelle con impatto economico o organizzativo passano a COO-CFO e CEO.", "Andamento personale e budget — trimestrale: previsione di organico, costo del lavoro, assunzioni e impatto sul budget."] },
  { code: "F", title: "Acquisti e fornitori", cadence: "Giornaliero - trimestrale", owner: "Ufficio acquisti e CFO-COO", steps: ["Fabbisogni e ordini — settimanale: priorità, materiali critici, spesa, budget, scostamenti e liquidità; le richieste oltre soglia vanno automaticamente in approvazione o rinvio.", "Prezzi e variazioni di costo — alert immediato su aumenti, anomalie rispetto allo storico o superamento del previsto.", "Fornitori e condizioni commerciali — trimestrale: prezzi, affidabilità, consegne, pagamenti e concentrazione acquisti.", "Ordini e consegne — giornaliero con alert su ritardi, ordini non confermati, consegne incomplete e materiali necessari a breve.", "Acquisti urgenti e fuori budget — immediato/entro 24 ore, sottoposti al CFO-COO per necessità operativa e sostenibilità.", "Acquisti e saving — mensile: valore, risparmio, scostamenti, urgenze e performance fornitori.", "Fabbisogno finanziario — trimestrale: acquisti futuri, contratti quadro e opportunità di negoziazione."] },
  { code: "G", title: "Contabilità e controllo amministrativo", cadence: "Giornaliero - trimestrale", owner: "Contabilità e CFO-COO", steps: ["Quadratura contabile — giornaliera: registrazioni, incassi, pagamenti, documenti mancanti e anomalie; criticità rilevanti al CFO-COO.", "Crediti e scaduti clienti — settimanale: incassi e insoluti; intervento CFO-COO sui clienti critici.", "Pagamenti fornitori — settimanale: scadenzario, previsione cash flow, priorità finanziarie e fornitori strategici.", "Documenti e competenza commesse — settimanale/alert: fatture, DDT, ordini, note spese e costi attribuiti a sede, reparto, commessa e centro di costo.", "Chiusura economico-contabile — entro il 10 del mese successivo: registrazioni e dati per conto economico, marginalità e scostamenti.", "Liquidità e tesoreria — settimanale: saldi, entrate, uscite, criticità, fabbisogno e vincoli di spesa.", "Alert amministrativi — immediato/entro 24 ore: fatture scadute, pagamenti anomali, documenti mancanti, budget, duplicazioni e incongruenze.", "Costi e scostamenti — mensile: confronto effettivo/budget per reparto, sede e commessa.", "Andamento finanziario — mensile/trimestrale: entrate, uscite, imposte, pagamenti, incassi e impegni futuri.", "Riunione CFO-COO-Contabilità — mensile: liquidità, insoluti, scadenze, anomalie, fuori budget, criticità commesse e decisioni."] },
  { code: "H", title: "Flussi dati e pratiche ADG/ADE", cadence: "Continuo - trimestrale", owner: "Ufficio dati e CTO", steps: ["Flussi dati — continui e automatici dal gestionale e dai sistemi aziendali; intervento solo su anomalie, dati mancanti o incoerenze.", "Alert e anomalie — giornaliero/entro 24 ore; il CTO interviene solo se serve approfondimento tecnico.", "Validazione pratiche — prima dell’invio: completezza e coerenza dall’ufficio, aspetti tecnici rilevanti dal CTO.", "Monitoraggio ADG/ADE — bisettimanale: pratiche in lavorazione, inviate, sospese, integrate o concluse, concentrandosi sulle eccezioni.", "Scadenze e richieste enti — alert 30/15/7 giorni su scadenze, integrazioni e attività da completare.", "Recuperi accise — mensile: importi richiesti, recuperati, pendenti e pratiche bloccate.", "Errori e automazioni — trimestrale: anomalie ricorrenti, nuovi controlli, regole e automatismi.", "Riepilogo CTO-Ufficio Dati — mensile: anomalie, pratiche critiche, recuperi, richieste enti e miglioramenti."] },
  { code: "H1", title: "Pianificazione e rilascio software", cadence: "Settimanale - trimestrale", owner: "CTO e sviluppatore", steps: ["Attività e priorità — settimanale: obiettivi e blocchi; le nuove richieste entrano nel piano senza interrompere automaticamente quanto già programmato.", "Avanzamento sviluppo — settimanale su RFID, CANbus, GPS, gestionale, checklist officina/lavaggio/verniciatura e automazioni: completato, in corso, bloccato, motivi e prossimi passi.", "Roadmap — mensile: percentuale rispetto al piano 12 mesi, scostamenti, ritardi, dipendenze e supporto.", "Integrazioni — ogni rilascio segue requisito → sviluppo → test → validazione CTO → rilascio → monitoraggio; niente funzioni critiche senza test.", "Personalizzazioni — settimanale: richieste raccolte nel gestionale e classificate dal CTO, senza modifiche dirette non autorizzate.", "Bug — continuo/alert: critici immediati, non critici pianificati.", "Documentazione tecnica — mensile: architettura, integrazioni, database, API, RFID, CANbus, GPS, varchi, antenne, tag e logiche, archiviate nel gestionale e non presso terzi.", "Verifica CTO-Sviluppo — trimestrale: realizzato rispetto agli obiettivi e priorità dei successivi tre mesi."] },
  { code: "I", title: "Sviluppo futuro", cadence: "Da definire", owner: "Direzione", steps: ["Da fare in funzione dello sviluppo — il documento originale lascia espressamente questa procedura da definire in funzione dello sviluppo."] },
  { code: "L", title: "Dati personale e formazione", cadence: "Continuo / alert 90-60-30-15-7 giorni", owner: "HR e Sicurezza", steps: ["HR mantiene aggiornati i dati nel gestionale; il Responsabile Sicurezza controlla formazione, abilitazioni e documenti intervenendo sulle anomalie automatiche. Scadenze e alert sono previsti a 90, 60, 30, 15 e 7 giorni."] },
  { code: "M", title: "Accessi, distacchi e preparazione cantieri", cadence: "Settimanale / previsionale", owner: "HR, Sicurezza, Operazioni e Commerciale", steps: ["Portali clienti e accessi — settimanale: abilitazioni aggiornate in anticipo, in particolare Logista Milano, Treviso e Roma; API dove disponibili, altrimenti attività manuali pianificate dal gestionale.", "Cantieri, personale e distacchi — previsione 30/60/90 giorni: incrocio tra cantieri, disponibilità, formazione, portali e distacchi; HR prepara i distacchi preferibilmente almeno 15 giorni prima.", "Coinvolgimento Commerciale — immediato: registrare anche richieste probabili, variazioni e possibili spostamenti senza aspettare la conferma definitiva.", "Spostamenti urgenti — verifica automatica preventiva di disponibilità, formazione, documenti, portale cliente e distacco; Sicurezza e HR intervengono sugli elementi mancanti.", "Controllo accesso — T-7 e T-2 giorni: il dipendente deve risultare completamente idoneo prima della partenza.", "Riunione HR-Sicurezza-Operazioni-Commerciale — settimanale 20/30 minuti, limitata alle eccezioni: cantieri imminenti, personale non pronto, formazione, portali, distacchi, picchi e urgenze."] },
  { code: "N", title: "Coordinamento logistico tra sedi", cadence: "Giornaliero - 30 giorni", owner: "Logistica generale e sedi", steps: ["Punto operativo — giornaliero: spedizioni, ritiri, materiali in arrivo, trasferimenti e priorità condivisi nel gestionale.", "Fabbisogni — settimanale: Milano e Treviso verificano con la Logistica Generale cantieri, officina e attività delle settimane successive.", "Trasferimenti Milano-Treviso — pianificati 48/72 ore prima e raggruppati dal gestionale per evitare viaggi singoli e urgenze.", "Materiali mancanti — alert anticipato con disponibilità nelle altre sedi, ordine in corso o necessità di acquisto.", "Richieste improvvise — immediate: prima si verifica il recupero interno, poi nuovi acquisti o trasporti dedicati.", "Scorte — settimanale: giacenze, materiali critici, sovrascorte e redistribuzioni.", "Picchi — previsione 15/30 giorni incrociando cantieri, ordini e attività.", "Confronto Logistica Generale-Milano-Treviso — settimanale 15/20 minuti sulle sole eccezioni: materiali, trasferimenti, ritardi, urgenze e settimana successiva."] },
  { code: "O", title: "Officina e manutenzioni", cadence: "Giornaliero - settimanale", owner: "Officina e Logistica", steps: ["Manutenzioni ordinarie — settimanale: checklist del gestionale con scadenze, attività, ricambi e priorità.", "Manutenzioni straordinarie — ticket immediato con macchina, problema, priorità e stato; registrazione di diagnosi, attività, ricambi e chiusura.", "Blocco macchina in cantiere — ticket URGENTE e report finale con causa, intervento, materiali, tempo e attività successive.", "Preparazione ricambi — giornaliera con alert automatici: la Logistica prepara ricambi, consumabili e materiali prima degli interventi.", "Dotazione ufficiale — controllo periodico: si usa solo attrezzatura aziendale censita e aggiornata nel gestionale.", "Attrezzatura mancante o inadeguata — segnalazione immediata alla Logistica; se non disponibile internamente, richiesta automatica agli Acquisti.", "Stato mezzi/macchine — giornaliero: disponibile / manutenzione programmata / guasto / fermo / pronto al rientro; la pianificazione usa solo mezzi realmente disponibili.", "Punto Logistica-Officina — settimanale 15/20 minuti: manutenzioni future, ticket, mezzi fermi, ricambi critici, attrezzature mancanti e problemi ricorrenti."] },
  { code: "P", title: "Trattamento e conformità dei materiali", cadence: "Giornaliero - settimanale", owner: "Logistica e reparti", steps: ["Programmazione — settimanale: materiali da lavare, riparare, verniciare o adeguare, con priorità, destinazione e data d’uso.", "Presa in carico — giornaliera con stati: da lavorare / in lavorazione / in attesa / completato / pronto al trasferimento.", "Lavaggio — checklist per lavorazione: pulizia, condizioni, anomalie e danni; invio automatico alla riparazione se necessario.", "Riparazione e Verniciatura Treviso — checklist programmata per tubazioni, morsetti, macchine e attrezzature destinate a Milano, con intervento, priorità e scadenza.", "Controllo prima del magazzino — obbligatori: spessori e misure; qualità verniciatura; colore e finitura; componenti, morsetti e accessori; funzionalità; conformità allo standard della sede destinataria.", "RFID — prima della chiusura: associazione di codice, tipologia, stato, sede e destinazione; il materiale senza identificazione corretta non viene trasferito.", "Trasferimenti intra-sede — 48/72 ore prima: soltanto materiali completati, verificati e validati RFID.", "Non conformità — alert e blocco automatico fino alla chiusura dell’anomalia.", "Fabbisogni futuri — 15/30 giorni: incrocio cantieri, richieste sedi e disponibilità per anticipare le lavorazioni.", "Punto Logistica-Reparti — settimanale 15/20 minuti sulle eccezioni: urgenze, ritardi, non conformità, attrezzature mancanti, trasferimenti e carichi futuri."] },
  { code: "Q", title: "Logistica automatizzata dall’ordine al rientro", cadence: "Tempo reale / settimanale", owner: "Logistica generale e di zona", steps: ["1. Ordine cliente — genera materiali e quantità, peso e volume, mezzo, distribuzione carico, personale, tempi e ritiri abbinabili; evidenzia subito carenze di materiali, mezzi o risorse.", "2. Previsione 7/15/30 giorni — carichi e ritiri, tonnellate, mulettisti, operatori carico/scarico, mezzi disponibili e trasportatori esterni; alert sui sovraccarichi.", "3. Preparazione 48/72 ore prima — stato: Disponibile / Da lavare / Da riparare / Da verniciare / Da verificare / Mancante; attività automatica al reparto competente.", "4. Alert reparti — Officina per guasti e manutenzioni; Lavaggio per sporco; Verniciatura per fuori standard; Logistica di Zona per ritardi e carenze. Priorità: T-72 avviso, T-48 alta, T-24 criticità.", "5. Controllo carico — peso, portata mezzo, distribuzione pesi, sequenza scarico, materiale presente e ritiro previsto; verifica ordine → materiale → RFID → quantità → peso → mezzo → personale → documentazione.", "6. RFID — confronto materiale ordinato → preparato → caricato → consegnato; alert per mancanze, articolo errato, duplicazioni, tag illeggibili e commessa sbagliata.", "7. Cantiere — registra materiale consegnato e presente, attrezzature non utilizzate, danni, materiale da ritirare, anomalie e sostituzioni; comunicazione in tempo reale alla Logistica di Zona.", "8. Ticket dal cantiere — Officina, Lavaggio, Verniciatura, sostituzione, ritiro o nuovo materiale.", "9. Ritiri e rientri — verifica quantità, peso, spazio, percorso e abbinamento con consegne; classificazione Pronto / Lavaggio / Riparazione / Verniciatura / Verifica / Dismissione; indisponibile fino a fine processo.", "10. Disponibilità futura — confronto tra fabbisogno prossimi cantieri e materiale disponibile + in rientro + in lavorazione, con alert anticipato.", "11. Dashboard unica — OGGI: carichi, ritiri, mezzi, personale, anomalie; 7 GIORNI: materiali critici, saturazione, risorse mancanti, lavori aperti; 30 GIORNI: picchi, carenze e necessità aggiuntive.", "12. Riunione operativa — settimanale 20 minuti sulle eccezioni: materiali non pronti, sovraccarichi, mezzi insufficienti, personale mancante, ritiri critici, ticket e consegne a rischio."] },
  { code: "R", title: "Arrivo merce e scarico", cadence: "Ad ogni consegna", owner: "Preposto e autista", steps: ["Ad ogni consegna il preposto affianca l’autista nel carico/scarico e verifica che il materiale consegnato corrisponda a quanto previsto."] },
  { code: "R1", title: "Controllo RFID", cadence: "Ad ogni movimentazione", owner: "Preposto", steps: ["Il preposto usa il lettore RFID per controllare materiale consegnato, presente, installato e da ritirare, aggiornando automaticamente il gestionale."] },
  { code: "R2", title: "Certificazione linea di pompaggio", cadence: "Prima del pompaggio e del rientro", owner: "Preposto", steps: ["Prima del pompaggio la lettura RFID verifica composizione e componenti della linea, certificando la posa di tubazioni, morsetti e coppiglie e registrandola nel gestionale.", "Anomalie — immediate: materiale mancante, errato, danneggiato o non riconosciuto genera alert a Logistica di Zona, Logistica Generale e Officina.", "Ritiro e chiusura — prima della partenza autista e preposto verificano materiale ritirato, materiale lasciato e stato attrezzature, chiudendo digitalmente la movimentazione."] },
  { code: "S", title: "Ciclo autobetoniere automatizzato", cadence: "Continuo / fine giornata", owner: "Autisti betoniere", steps: ["Inizio giornata — automatico GPS/CAN bus: partenza, mezzo, orario e posizione.", "Carico CLS — automatico con scansione bolla: GPS e CAN bus registrano sosta e ripartenza; l’autista scansiona la bolla con il palmare e la associa al viaggio.", "Trasporto e arrivo — automatico: percorso, arrivo, permanenza e ripartenza collegati alla consegna.", "Carichi successivi — automatici: stabilimento → carico → cantiere → scarico → ritorno; l’unica azione manuale è acquisire ogni nuova bolla.", "Anomalie — solo se necessarie: ritardi, cambio cantiere, problemi mezzo, contestazioni o anomalie bolla; le attività normali restano automatizzate.", "Rapportino di fine giornata — automatico con orari, stabilimenti, cantieri, viaggi, soste, chilometri, permanenze e bolle associate."] },
  { code: "T", title: "Gestione impianto e cantiere", cadence: "Giornaliero - mensile", owner: "Responsabile di commessa", steps: ["Pianificazione giornaliera/settimanale — volumi CLS, turni, personale, autobetoniere, pompaggio, pala e attività, incluse notturne e festive.", "Impianto e produzione CLS — verifica materiali, stato impianto, quantità e anomalie; fermi e problemi vanno segnalati subito.", "Trasporto e pompaggio intracantiere — tracciamento di viaggi, orari, quantità, soste, fermi e criticità.", "Inerti, pulizia e manutenzione — personale abilitato su pala e scorte; a fine ciclo/turno pulizia di impianto, betoniere e linee, più manutenzione ordinaria.", "Turni straordinari, notturni e festivi — pianificati in anticipo con personale, attività, mezzi e responsabilità.", "Anomalie e fermo impianto — registrazione di causa, orario, impatto, intervento e tempo di ripristino.", "Dati e rapportini — giornalieri: acquisizione automatica di produzione, viaggi, ore, mezzi e fermi; nella transizione resta il rapportino manuale.", "Quadratura e contabilità cantiere — settimanale/mensile: coerenza tra CLS, viaggi, pompaggio, ore personale, ore mezzi e costi; segnalazione scostamenti.", "Riunione operativa — settimanale: produzione, programma, turni, manutenzioni, fermi, anomalie e andamento economico."] },
  { code: "U1", title: "Coordinamento operativo del preposto", cadence: "Giornaliero / continuo", owner: "Preposto", steps: ["Briefing — giornaliero: il preposto riceve gli obiettivi e assegna le attività agli operatori qualificati, che coordinano gli altri operatori; chiarisce priorità, tempi, mezzi, attrezzature e responsabilità.", "Rapportino — fine turno durante la transizione: personale presente; attività svolte; ore lavorate; fermi; manutenzioni; anomalie; materiali utilizzati; criticità e attività da completare.", "Chiusura e passaggio consegne — fine turno: stato lavorazioni, attrezzature, pulizia, sicurezza area, attività del giorno successivo e segnalazioni aperte nel gestionale."] },
  { code: "U2", title: "Sicurezza, qualità ed escalation", cadence: "Continuo / immediato", owner: "Preposto e operatori", steps: ["Avanzamento lavori — continuo: rispetto del programma, intervento sui ritardi e riorganizzazione risorse.", "Pause di getto — ad ogni interruzione utile: manutenzione ordinaria, controlli, pulizia, riordino e preparazione delle fasi successive.", "Pulizia e cura — durante e a fine turno: macchine, tubazioni, morsetti, utensili e aree in corrette condizioni.", "Sicurezza e DPI — controllo continuo; in situazione pericolosa il preposto interrompe e segnala immediatamente.", "Attrezzature e materiali — inizio giornata/durante il turno: disponibilità e idoneità di personale, mezzi, attrezzature e materiali; segnalazione delle mancanze.", "Anomalie — immediate: guasti, sicurezza, non conformità, ritardi, errori o condizioni critiche, senza attendere fine giornata.", "Gestione operatori — continua: indicazioni dal preposto agli operatori qualificati e a cascata agli altri; verifica di comprensione ed esecuzione.", "Qualità — per ogni fase rilevante: rispetto di indicazioni, standard aziendali e specifiche di cantiere per evitare rilavorazioni e contestazioni.", "Imprevisti ed escalation — immediata: coinvolgere responsabile di zona o funzione competente indicando problema, impatto, possibile soluzione e urgenza."] },
];

export function dutiesForCode(code: string) {
  return dutyGroups.flatMap((group) => group.codes.includes(code) ? group.items : []);
}
